### ISSUE TITLE
Minimum required version 0.07 of prerequisite Crypt::Random::Source throws warnings

### ISSUE THREAD

**Issue by McA** [frioux/Math-Random-Secure#2]
If you have version 0.07 of Crypt::Random::Source the necessary prerequisite is fullfilled. But in this case you get the following runtime warning in certain usage scenarios.
Please update the Makefile. There are some interesting changes in Crypt::Random::Source  which may be considered in the declaration of the minimum version.

Class::MOP::load_class is deprecated at /opt/drumedar/cpan/lib/perl5/x86_64-linux-thread-multi/Class/MOP.pm line 69.
        Class::MOP::load_class('Crypt::Random::Source::Weak::rand') called at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 137
        eval {...} called at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 137
        Crypt::Random::Source::Factory::best_available('Crypt::Random::Source::Factory=HASH(0x1ad4b40)', 'Crypt::Random::Source::Weak::rand', 'Crypt::Random::Source::Weak::devurandom') called at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 50
        Crypt::Random::Source::Factory::_build_weak_source('Crypt::Random::Source::Factory=HASH(0x1ad4b40)') called at accessor Crypt::Random::Source::Factory::weak_source (defined at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 40) line 10
        Crypt::Random::Source::Factory::weak_source('Crypt::Random::Source::Factory=HASH(0x1ad4b40)') called at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 76
        Crypt::Random::Source::Factory::_build_any_source('Crypt::Random::Source::Factory=HASH(0x1ad4b40)') called at accessor Crypt::Random::Source::Factory::any_source (defined at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 66) line 10
        Crypt::Random::Source::Factory::any_source('Crypt::Random::Source::Factory=HASH(0x1ad4b40)') called at /opt/drumedar/cpan/lib/perl5/x86_64-linux-thread-multi/Moose/Meta/Method/Delegation.pm line 93
        Crypt::Random::Source::Factory::new_any('Crypt::Random::Source::Factory=HASH(0x1ad4b40)') called at /home/mca/paketversuche/lib/perl5/Crypt/Random/Source/Factory.pm line 27
        Crypt::Random::Source::Factory::get('Crypt::Random::Source::Factory=HASH(0x1ad4b40)') called at /home/mca/paketversuche/lib/perl5/Math/Random/Secure/RNG.pm line 95
        Math::Random::Secure::RNG::_build_seeder('Math::Random::Secure::RNG=HASH(0x1ad4b70)') called at (eval 203) line 18
        Math::Random::Secure::RNG::seeder('Math::Random::Secure::RNG=HASH(0x1ad4b70)') called at /home/mca/paketversuche/lib/perl5/Math/Random/Secure/RNG.pm line 106
        Math::Random::Secure::RNG::_build_seed('Math::Random::Secure::RNG=HASH(0x1ad4b70)') called at (eval 204) line 43
        Math::Random::Secure::RNG::seed('Math::Random::Secure::RNG=HASH(0x1ad4b70)') called at /home/mca/paketversuche/lib/perl5/Math/Random/Secure.pm line 60
        Math::Random::Secure::srand() called at /home/mca/paketversuche/lib/perl5/Math/Random/Secure.pm line 28
        Math::Random::Secure::irand(4) called at -e line 1

**Comment by frioux** [comment]
It looks like version 0.07 is incompatible with modern Moose.  That's not really relevant to this package
